const ACTIONS = {
    FETCH_INDUSTRY_REQUEST: "MANAGE_INDUSTRY_REQUEST",
    FETCH_INDUSTRY_SUCCESS: "MANAGE_INDUSTRY_SUCCESS",
    FETCH_INDUSTRY_FAILURE: "MANAGE_INDUSTRY_FAILURE",

    FETCH_DEPARTMENT_REQUEST: "MANAGE_DEPARTMENT_REQUEST",
    FETCH_DEPARTMENT_SUCCESS: "MANAGE_DEPARTMENT_SUCCESS",
    FETCH_DEPARTMENT_FAILURE: "MANAGE_DEPARTMENT_FAILURE",

    FETCH_DIVISIONS_REQUEST: "MANAGE_DIVISIONS_REQUEST",
    FETCH_DIVISIONS_SUCCESS: "MANAGE_DIVISIONS_SUCCESS",
    FETCH_DIVISIONS_FAILURE: "MANAGE_DIVISIONS_FAILURE",

    FETCH_COUNTRY_REQUEST: "MANAGE_COUNTRY_REQUEST",
    FETCH_COUNTRY_SUCCESS: "MANAGE_COUNTRY_SUCCESS",
    FETCH_COUNTRY_FAILURE: "MANAGE_COUNTRY_FAILURE",

    FETCH_STATE_REQUEST: "MANAGE_STATE_REQUEST",
    FETCH_STATE_SUCCESS: "MANAGE_STATE_SUCCESS",
    FETCH_STATE_FAILURE: "MANAGE_STATE_FAILURE",

    FETCH_CITY_REQUEST: "MANAGE_CITY_REQUEST",
    FETCH_CITY_SUCCESS: "MANAGE_CITY_SUCCESS",
    FETCH_CITY_FAILURE: "MANAGE_CITY_FAILURE"
    
};

export default ACTIONS;
